### ISSUE TITLE
Java package name and Maven groupId

### ISSUE THREAD

**Issue by Awerin** [erasmus-without-paper/ewp-java-libs#1]
The naming convention for a java package is to use the reversed Internet domain of the company that created the software (https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html):

Which package name should we use:

* pl.edu.usos
* eu.erasmuswithoutpaper
* else?

PS. The appropriate package name will be used as the Maven groupId.

**Comment by wrygiel** [comment]
BTW, if you want everyone notified about the issue you can @mention the developers group.

**Comment by Awerin** [comment]
@erasmus-without-paper/developers, please comment.

**Comment by vickalaser** [comment]
I would suggest the second option. Assuming long life and cross European take up, we want a clear identification with the EU funded project.

**Comment by mikesteez** [comment]
I also agree, the most intuitive would be to have eu.erasmuswithoutpaper as the package name.

**Comment by dorlando** [comment]
I agrree with the second option

**Comment by megachirone** [comment]
I agree with the second option!

**Comment by vmmaSigmaaie** [comment]
I agree with the second option too, but maybe the package name could be reduced to eu.ewp

**Comment by wrygiel** [comment]
ewp.eu is already "taken" - http://www.ewp.eu/

**Comment by huntering** [comment]
Erasmus without papers, is this a project or a product name?
There might be other projects continuing on this work. The next project might be named erasmusautomation. Should we then start renaming all this work?
We are supporting the "erasmus programme", so why not _erasmus.eu_ ?
Or maybe _eramusnetwork _to give it a technical hint or shorter _ern.eu_ maybe even broader _studentexchangenetwork.eu_ or _sen.eu._

**Comment by Awerin** [comment]
> Erasmus without papers, is this a project or a product name?

@huntering, could you give an example of the difference? I'm not sure which definition you are refering to.

> There might be other projects continuing on this work. The next project might be named erasmusautomation. Should we then start renaming all this work?

Could you give an example? Why would we need to rename the package for EWP when an other project emerges?

> We are supporting the "erasmus programme", so why not erasmus.eu ?

I'm not sure if we can use it as a package name. Maybe we should be given some consent for that? @erasmus-without-paper/developers, please comment.

> Or maybe eramusnetwork to give it a technical hint or shorter _ern.eu maybe even broader _studentexchangenetwork.eu or sen.eu.

I was under the impression that we should stick to domain names but maybe that's not that important, @erasmus-without-paper/developers?

If I understand your concerns you are looking for a more general name than the name of the project - Erasmus Without Papers. Am I right?

**Comment by Awerin** [comment]
I'm starting with `eu.erasmuswithoutpaper` package name. I might change that if we vote for some other name in the future.
