### ISSUE TITLE
General design of EWP security libraries

### ISSUE THREAD

**Issue by Awerin** [erasmus-without-paper/ewp-java-libs#2]
After some thought I have sketched two libraries that will be used for EWP security implementation:
- _ewp-security-web_ - library responsible for authentication.
  - Requires: _Servlet API 3.0_ (or higher). That way it can be used by EWP partners that use a security framework other than Spring Security.
  - Defines _servlets_ and _filters_. Stores information about the "principal" in a _HttpServletRequest_ wrapper.
- _ewp-security-spring_ - library that connects _ewp-security-web_ with Spring Security.
  - Requires: _ewp-security-web_ and _Spring Security 3.x_ (or higher).
  - Defines an _AuthenticationEntryPoint_ responsible for EWP security.

@erasmus-without-paper/developers, please comment. I will be adding more proposals and details as they appear.

PS. All libraries will require Java 1.6 or higher.

**Comment by mpuzar** [comment]
As we don't use Spring, I vote for the non-Spring version.

**Comment by Awerin** [comment]
During one of the conferences at Warsaw it has been stated that there is no need for a library that would try to address EWP security issues in an abstract way (not tied to a particular Java framework). Partners will probably want to write the security part of their connector themselves.
